---
- hosts: 172.31.29.29
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    register: myresult
  - name: i want to display my first task result
    debug:
      msg: "{{myresult}}"
