---
- hosts: 172.31.29.29
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
  - name: install apache2
    apt:
      name: apache2
      stateee: present
    ignore_errors: true
  - name: install wget
    apt:
      name: wget
      state: present