---
- hosts: 172.31.29.29
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: copy file into asnible side nodes
    copy: 
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt
  - name: copy index.j2 file into ansible node side
    template:
      src: index.j2
      dest: /var/www/html/index.html
  - name: Download file and force basic auth
    ansible.builtin.get_url:
      url: https://www.jenkins.io/doc/book/installing/linux/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes
    

