---
- hosts: 172.31.29.29
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: copy file into asnible side nodes
    copy: 
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt
